# Generated by Django 3.1.2 on 2021-05-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210527_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='music',
        ),
    ]
