# Generated by Django 3.1.2 on 2021-05-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='num_favourite',
        ),
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
