# Generated by Django 3.1.2 on 2021-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210528_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
