<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-06-04 02:21
=======
# Generated by Django 3.1.2 on 2021-06-04 03:03
>>>>>>> 76837ce1f6b5cc26c9236b110814e2f6c34220b5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_music_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='num_favourite',
            field=models.IntegerField(default=0),
        ),
    ]
