# Generated by Django 3.1.2 on 2021-05-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=300)),
                ('urli', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='')),
            ],
        ),
    ]
